language: python
python:
  - "3.7"
  - "3.8"
 
 
 install:
  - pip install art  # Install the art package
  
  
# command to run tests
script:
  - python test_board.py
  - python test_game.py
  - python test_player.py
  - python test_snakeandladdder.py
  - python test_util.py